global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'account-api'
    static_configs:
      - targets: ['api:5001']  # 5001 is the port exposed by the account-api container